repos:
  - repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
      - id: black
        files: app/
  - repo: https://github.com/pycqa/pylint
    rev: v2.11.1
    hooks:
      - id: pylint
        files: app/
        exclude: ^migrations/
        args:
          - --rcfile=./.pylintrc
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''
    hooks:
      - id: mypy
        files: app/
        additional_dependencies: 
          - pydantic
