version: "3.9"

services:

  postgres:
    image: postgres
    env_file: .env
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file: .env
    ports:
      - "5050:80"
    depends_on:
      - postgres