version: "3.9"

services:

  postgres_test:
    container_name: db_test
    image: postgres:12
    env_file: .env.test
    ports:
      - 5433:5432
    # volumes:
    #   - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    networks:
      - test

networks:
  test:
    name: test