name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.9
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:12
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: user
          POSTGRES_DB: billing_test

        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.10
          virtualenvs-create: true
          virtualenvs-in-project: false
      
      - name: Move poetry dependencies to standart requirements.txt
        run: |
          poetry export --dev -f requirements.txt --output requirements.txt
          pip install --no-cache-dir -r requirements.txt

      - name: Run linter
        run: make lint

      - name: Run tests
        env:
          BILLING_DB_DSN: postgresql://user:password@localhost:5432/billing_test

        run: |
          touch .env.test
          make alembic-upgrade
          make test
