name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Populate .env file
        run: |
          echo """
            POSTGRES_DB=billing
            PGDATA=/var/lib/postgresql/data/billing_app
            POSTGRES_USER=user
            POSTGRES_PASSWORD=password
            DB_HOST=postgres
            DB_PORT=5432
            PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
            PGADMIN_DEFAULT_PASSWORD=admin
            APP_ENV=development
          """ > .env

      - name: Populate .env.test file
        run: |
          echo """
            APP_ENV=test
            POSTGRES_DB=billing_test
            PGDATA=/var/lib/postgresql/data/billing_app_test
            DB_HOST=postgres_test
            DB_PORT=5432
            POSTGRES_USER=user
            POSTGRES_PASSWORD=password
          """ > .env.test

      - name: Run tests
        run: |
          docker-compose -f docker-compose.test.yml up -d --force-recreate
          docker ps -a
          docker-compose run billing_app bash -c "pytest"
